# -*- coding: utf-8 -*-
# Copyright (C) 2016-Today: GRAP (http://www.grap.coop)
# @author: Sylvain LE GAL (https://twitter.com/legalsylvain)
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).


- !record {model: product.product, id: administrative_product}:
    name: Global Administrative Product
    categ_id: product.product_category_all
    uom_id: product.product_uom_unit
    uom_po_id: product.product_uom_unit
    administrative_ok: True
    company_id: base_fiscal_company.company_fiscal_mother

- !record {model: product.product, id: product_A_CH1}:
    name:  Product A of CH1
    categ_id: product.product_category_all
    uom_id: product.product_uom_unit
    uom_po_id: product.product_uom_unit
    sale_ok: True
    company_id: base_fiscal_company.company_fiscal_child_1
    list_price: 15.0

- !record {model: product.product, id: product_B_CH1}:
    name:  Product B of CH1
    categ_id: product.product_category_all
    uom_id: product.product_uom_unit
    uom_po_id: product.product_uom_unit
    sale_ok: True
    company_id: base_fiscal_company.company_fiscal_child_1
    list_price: 22.0
