# -*- coding: utf-8 -*-
# Copyright (C) 2016-Today: GRAP (http://www.grap.coop)
# @author: Sylvain LE GAL (https://twitter.com/legalsylvain)
# License AGPL-3.0 or later (http://www.gnu.org/licenses/agpl.html).


- !record {model: product.product, id: administrative_product}:
    name: Global Administrative Product
    categ_id: product.product_category_all
    administrative_ok: True
    company_id: base_fiscal_company.company_fiscal_mother
